name: stomp-client
on: 
  push:
    branches:
      - master
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "%s"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
