name: stomp-client
on: 
  push:
    branches:
      - master
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm publish
      - env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
